name: Python Async CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: rafal
          POSTGRES_PASSWORD: lelito
          POSTGRES_DB: user_app
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 app tests

      - name: Run tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///./test.db
        run: |
          pytest -v

  docker_build:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker build images
        run: docker build -t myapp:latest .

      - name: List Docker images
        run: docker images
